version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always  # Recommended for stability
    environment:
      MYSQL_ROOT_PASSWORD: akshit
      MYSQL_DATABASE: chat_app
      MYSQL_USER: akshit  # Use a non-root user (or remove this line)
      MYSQL_PASSWORD: akshit
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
    volumes:
      - mysql_data:/var/lib/mysql

  boot-app:
    image: akshit/chatback
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/chat_app
      - SPRING_DATASOURCE_USERNAME=akshit  # Matches MYSQL_USER
      - SPRING_DATASOURCE_PASSWORD=akshit
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:

volumes:
  mysql_data:
